"""initial migration

Revision ID: 4d84e50d8b4
Revises: None
Create Date: 2015-04-09 20:55:24.972676

"""

# revision identifiers, used by Alembic.
revision = '4d84e50d8b4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('literary_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=3), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('creation_datestring', sa.String(length=63), nullable=True),
    sa.Column('original_lang', sa.String(length=3), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=63), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=3), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['genres_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_lang', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literary_works_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_lang', sa.String(length=3), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['literary_works_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literary_works_2_series',
    sa.Column('literary_work_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['literary_work_id'], ['literary_works.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['literary_works_series.id'], ),
    sa.PrimaryKeyConstraint('literary_work_id', 'series_id', 'position')
    )
    op.create_table('literary_works_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('literary_work_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mime_type', sa.String(length=63), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('original_file_ext', sa.String(length=255), nullable=True),
    sa.Column('binary_data', sa.LargeBinary(length=134217728), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['literary_work_id'], ['literary_works.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['literary_works_storage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literary_works_2_genres',
    sa.Column('literary_work_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['literary_work_id'], ['literary_works.id'], ),
    sa.PrimaryKeyConstraint('literary_work_id', 'genre_id')
    )
    op.create_table('literary_works_series_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=3), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['literary_works_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors_2_literary_works',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('literary_work_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['literary_work_id'], ['literary_works.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'literary_work_id')
    )
    op.create_table('authors_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=3), nullable=False),
    sa.Column('last_name', sa.String(length=63), nullable=False),
    sa.Column('first_name', sa.String(length=63), nullable=True),
    sa.Column('middle_name', sa.String(length=63), nullable=True),
    sa.Column('nickname', sa.String(length=127), nullable=True),
    sa.Column('wikipedia_hyperlink', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_details_last_name'), 'authors_details', ['last_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_details_last_name'), table_name='authors_details')
    op.drop_table('authors_details')
    op.drop_table('authors_2_literary_works')
    op.drop_table('literary_works_series_details')
    op.drop_table('literary_works_2_genres')
    op.drop_table('literary_works_storage')
    op.drop_table('literary_works_2_series')
    op.drop_table('literary_works_series')
    op.drop_table('authors')
    op.drop_table('genres_details')
    op.drop_table('genres')
    op.drop_table('literary_works')
    ### end Alembic commands ###
