"""multilingual literary_works details and storage support

Revision ID: 531bf3c3a95
Revises: 53709fe8e8e
Create Date: 2015-04-16 20:28:26.647596

"""

# revision identifiers, used by Alembic.
revision = '531bf3c3a95'
down_revision = '53709fe8e8e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('literary_works_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('literary_work_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('annotation', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['literary_work_id'], ['literary_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('literary_works', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('literary_works', 'original_lang',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.drop_column('literary_works', 'lang')
    op.drop_column('literary_works', 'added')
    op.drop_column('literary_works', 'annotation')
    op.drop_column('literary_works', 'title')
    op.add_column('literary_works_storage', sa.Column('literary_work_details_id', sa.Integer(), nullable=False))
    op.drop_constraint('literary_works_storage_literary_work_id_fkey', 'literary_works_storage', type_='foreignkey')
    op.create_foreign_key(None, 'literary_works_storage', 'literary_works_details', ['literary_work_details_id'], ['id'])
    op.drop_column('literary_works_storage', 'literary_work_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('literary_works_storage', sa.Column('literary_work_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'literary_works_storage', type_='foreignkey')
    op.create_foreign_key('literary_works_storage_literary_work_id_fkey', 'literary_works_storage', 'literary_works', ['literary_work_id'], ['id'])
    op.drop_column('literary_works_storage', 'literary_work_details_id')
    op.add_column('literary_works', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('literary_works', sa.Column('annotation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('literary_works', sa.Column('added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('literary_works', sa.Column('lang', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.alter_column('literary_works', 'original_lang',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.drop_column('literary_works', 'timestamp')
    op.drop_table('literary_works_details')
    ### end Alembic commands ###
